version: '1.0'
services:
  server:
    build: .
    image: cccc-auto-check-in:${TAG:-latest}
    container_name: cccc-auto-check-in
    volumes:
      - ./logs:/app/logs
    mem_limit: 2G
    memswap_limit: -1
    restart: unless-stopped
    tty: True
    command: python main.py run
